name: Raspberry Pi Python 3.9 CI

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('RaspberryPi/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Verificar estrutura do projeto
        run: |
          echo "Estrutura do projeto:"
          ls -la
          echo "Conteúdo da pasta RaspberryPi (se existir):"
          ls -la RaspberryPi/ || echo "Pasta RaspberryPi não encontrada"

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          if [ -f "RaspberryPi/requirements.txt" ]; then
            pip install -r RaspberryPi/requirements.txt
          else
            echo "Arquivo requirements.txt não encontrado em RaspberryPi/"
            # Instalar dependências básicas para Bluetooth/Raspberry Pi
            pip install bluetooth-python pybluez pytest
          fi

      - name: Verificar instalação Python
        run: |
          python --version
          pip list

      - name: Rodar testes
        run: |
          if [ -f "RaspberryPi/test_bt_server.py" ]; then
            echo "Executando testes com pytest..."
            pytest RaspberryPi/ -v
          elif [ -f "RaspberryPi/bt_server.py" ]; then
            echo "Executando verificação de sintaxe do servidor Bluetooth..."
            python -m py_compile RaspberryPi/bt_server.py
          else
            echo "Nenhum arquivo de teste ou servidor encontrado"
            echo "Criando um teste básico de importação..."
            python -c "
try:
    import bluetooth
    print('✓ Bluetooth library importada com sucesso')
except ImportError as e:
    print('⚠ Bluetooth library não disponível:', e)
    print('Isso é normal em ambiente CI/Ubuntu')
            "
          fi

      - name: Upload logs se houver erro
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: test-logs
          path: |
            *.log
            RaspberryPi/*.log
          retention-days: 3